version: '3.7'

services:
  app_igs:
    container_name: python_app_admin_igs
    build:
      context: ./app-admin
    #image: python:latest
    restart: always
    ports:
      - '80:8000'
    volumes:
      - ./app-admin:/usr/src/app
    links:
      - postgres_igs

  api_igs:
    container_name: python_api_igs
    build:
      context: ./api
    #image: python:latest
    # restart: always
    ports:
      - '5000:8000'
    volumes:
      - ./api/:/usr/src/app
    depends_on:
      - postgres_igs
    links:
      - postgres_igs

  postgres_igs:
    container_name: postgres_igs
    build:
       context: ./db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      #PG_DATA: /var/lib/postgresql/data/
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: